name: Bug Report \ 问题反馈
description: Create a report to help us improve \ 帮助改进
labels: ["Bug"]

body:
  - type: input
    id: title
    attributes:
      label: Title \ 标题
      description: A brief summary of the bug. \ 对于该错误的简要总结。
      placeholder: Enter the bug title here. \ 在此输入错误标题。
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce \ 操作流程
      description: Steps to reproduce the behaviour. \ 重现该行为的步骤。
      placeholder: |
        1. Go to '...' \ 1. 进入 '...'
        2. Click on '....' \ 2. 点击 '....'
        3. Scroll down to '....' \ 3. 向下滚动到 '....'
        4. See error \ 4. 查看错误
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour \ 预期结果
      description: A clear and concise description of what you expected to happen. \ 对您期望发生的事情的清晰简明描述。
      placeholder: A clear and concise description of what you expected to happen. \ 对您期望发生的事情的清晰简明描述。
    validations:
      required: true

  - type: textarea
    id: software-version
    attributes:
      label: Software Version \ 软件版本
      description: Please specify the version of the software you are using. \ 请指定您使用的软件版本。
      placeholder: Enter the software version here. \ 在此输入软件版本。
    validations:
      required: true
